version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - apt-get update && apt-get install -y cmake gcc valgrind

  pre_build:
    commands:
      - echo "Building external projects..."
      - git submodule update --init --recursive
      - cd extern/aws-lambda-cpp
      - mkdir build
      - cd build
      - cmake .. -DCMAKE_BUILD_TYPE=Release
      - make && make install
      - cd -

  build:
    commands:
      - echo "Building the application..."
      - mkdir build
      - cd build
      - cmake .. -DCMAKE_BUILD_TYPE=Release
      - make
      - echo "Running Tests..."
      - ctest -V

  post_build:
    commands:
      - if [ "$CODEBUILD_WEBHOOK_EVENT" == "PULL_REQUEST_MERGED" ]; then
          echo "Packaging and deploying the application..."
          make aws-lambda-package-SudokuLambda
          mv SudokuLambda.zip ../
        else
          echo "Skipping packaging and deployment for pull requests."
        fi

artifacts:
  files:
    - if [ "$CODEBUILD_WEBHOOK_EVENT" == "PULL_REQUEST_MERGED" ]; then
        backend/SudokuLambda.zip
      fi
aws_codepipeline:
  enabled: true
