version: 0.2

env:
  git-credential-helper: yes
  variables:
    NPM_CACHE_DIR: "$HOME/.npm"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing source NPM dependencies...
      - cd $CODEBUILD_SRC_DIR/frontend
      - npm config set cache "$NPM_CACHE_DIR"
      - npm ci --no-audit --no-fund

  test:
    commands:
      - cd $CODEBUILD_SRC_DIR/frontend
      - echo "Running Tests..."
      - npm run test:ci
      - npm run lint:check

reports:
  unittest-reports:
    files: "junit.xml"
    base-directory: frontend/test-results
    discard-paths: yes
    file-format: JUNITXML
  coverage-report:
    files: "clover.xml"
    base-directory: frontend/coverage
    discard-paths: yes
    file-format: CLOVERXML

cache:
  paths:
    - frontend/node_modules/**/*
    - $HOME/.npm/**/*
