version: 0.2

env:
  git-credential-helper: yes

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - yum -y update
      - yum -y install cmake gcc boost-devel boost-json

  pre_build:
    commands:
      - echo "Building external projects..."
      - cd $CODEBUILD_SRC_DIR/backend/extern/aws-lambda-cpp
      - mkdir build
      - cd build
      - cmake .. -DCMAKE_BUILD_TYPE=Release
      - make && make install

  build:
    commands:
      - echo "Building the application..."
      - cd $CODEBUILD_SRC_DIR/backend
      - mkdir build
      - cd build
      - cmake .. -DCMAKE_BUILD_TYPE=Release
      - make
      - echo "Running Tests..."
      - ctest -V

  post_build:
    commands:
      - |
        if [ "$CODEBUILD_WEBHOOK_EVENT" == "PULL_REQUEST_MERGED" ]; then
          echo "Packaging and deploying the application..."
          make aws-lambda-package-SudokuLambda
          mv SudokuLambda.zip ../
        else
          echo "Skipping packaging and deployment for pull requests."
        fi

reports:
  unittest_reports:
    files: 'unittest.xml'
    base-directory: 'backend/build/tests/unittest_reports/'
    discard-paths: no
    file-format: JUnit

artifacts:
  files: $CODEBUILD_SRC_DIR/backend/SudokuLambda.zip
  if: CODEBUILD_WEBHOOK_EVENT == 'PULL_REQUEST_MERGED'
