version: 0.2

env:
  git-credential-helper: yes

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - yum -y update
      - |
        yum -y install cmake \
                       gcc \
                       libomp \
                       boost-devel \
                       boost-json

  pre_build:
    commands:
      - echo "Setting up the environment..."
      - export FUCTION_NAME="SudokuSolverBackend"
      - export VERSION=$(grep -oP '\[\K[0-9]+\.[0-9]+\.[0-9]+' CHANGELOG.md | head -1)
      - |
        if [ "$CODEBUILD_WEBHOOK_TRIGGER" == "branch/main" ]; then
          export CMAKE_BUILD_TYPE="Release"
          export GIT_REVISION=$(git rev-list HEAD --count)
          export ARTIFACT_NAME="${CMAKE_BUILD_TYPE}/${VERSION}/${GIT_REVISION}"
        else
          export CMAKE_BUILD_TYPE="Debug"
          export DATE=$(date +%Y%m%d%H%M%S)
          export ARTIFACT_NAME="${CMAKE_BUILD_TYPE}/${VERSION}/${DATE}"
        fi
      - echo "CMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE"
      - echo "VERSION=$VERSION"
      - echo "ARTIFACT_NAME=$ARTIFACT_NAME"

  build:
    commands:
      - echo "Building external projects..."
      - |
        cd $CODEBUILD_SRC_DIR/backend/extern/aws-lambda-cpp
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE \
                 -DBUILD_SHARED_LIBS=OFF \
                 -DCMAKE_INSTALL_PREFIX=$CODEBUILD_SRC_DIR/backend
        make && make install
      - echo "Building the application..."
      - |
        cd $CODEBUILD_SRC_DIR/backend
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE \
                 -DCMAKE_PREFIX_PATH=$CODEBUILD_SRC_DIR/backend
        make
      - echo "Running Tests..."
      - ctest -V -L sudoku --output-on-failure
      - echo "Running Benchmarks..."
      - ../bin/bench
      - echo "Building package..."
      - make aws-lambda-package-$FUCTION_NAME

  post_build:
    commands:
      - |
        if [ "$CODEBUILD_WEBHOOK_TRIGGER" == "branch/main" ]; then
          echo "Tagging the version..."
          git tag ${VERSION}-${GIT_REVISION}
          git push origin ${VERSION}-${GIT_REVISION}
          echo "Tagged the version: ${VERSION}-${GIT_REVISION}"
          if [ -f $CODEBUILD_SRC_DIR/backend/build/src/handler/$FUCTION_NAME.zip ]; then
            echo "Uploading to aws lambda"
            aws lambda update-function-code --function-name $FUCTION_NAME --zip-file fileb://$CODEBUILD_SRC_DIR/backend/build/src/handler/$FUCTION_NAME.zip
          fi
        fi

reports:
  unittest-reports:
    base-directory: backend/build/tests/unittest-reports
    files: "*.xml"
    discard-paths: yes
    file-format: JUNITXML

artifacts:
  files: backend/build/src/handler/$FUCTION_NAME.zip
  name: $ARTIFACT_NAME
  discard-paths: yes
