version: 0.2

env:
  git-credential-helper: yes

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - yum -y update
      - yum -y install cmake gcc boost-devel boost-json valgrind

  pre_build:
    commands:
      - echo "Setting up the environment..."
      - export VERSION=$(grep -oP '\[\K[0-9]+\.[0-9]+\.[0-9]+' CHANGELOG.md | head -1)
      - |
        if [ "$CODEBUILD_WEBHOOK_EVENT" == "PULL_REQUEST_MERGED" ]; then
          export CMAKE_BUILD_TYPE="Release"
          export ARTIFACT_NAME="SudokuLambda-${VERSION}-${CMAKE_BUILD_TYPE}"
        else
          export CMAKE_BUILD_TYPE="Debug"
          export ARTIFACT_NAME="SudokuLambda-${VERSION}-${CMAKE_BUILD_TYPE}-${CODEBUILD_START_TIME}"
        fi
      - echo "CMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE"
      - echo "VERSION=$VERSION"
      - echo "ARTIFACT_NAME=$ARTIFACT_NAME"

  build:
    commands:
      - echo "Building external projects..."
      - cd $CODEBUILD_SRC_DIR/backend/extern/aws-lambda-cpp
      - mkdir build
      - cd build
      - cmake .. -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE
      - make && make install
      - echo "Building the application..."
      - cd $CODEBUILD_SRC_DIR/backend
      - mkdir build
      - cd build
      - cmake .. -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE
      - make && make aws-lambda-package-SudokuLambda
      - echo "Running Tests..."
      - ctest -V

  post_build:
    commands:
      - echo "Deploying the application..."
      - mv $CODEBUILD_SRC_DIR/backend/build/src/handler/SudokuLambda.zip $CODEBUILD_SRC_DIR/backend/$ARTIFACT_NAME.zip
      - |
        if [ "$CODEBUILD_WEBHOOK_EVENT" == "PULL_REQUEST_MERGED" ]; then
          git tag ${VERSION}
          git push origin ${VERSION}
          echo "Tagged the version: ${VERSION}"
        fi

reports:
  unittest_reports:
    files: backend/build/tests/unittest_reports/unittest.xml
    file-format: JUnit

artifacts:
  files: backend/$ARTIFACT_NAME.zip
