version: 0.2

env:
  git-credential-helper: yes

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - yum -y update
      - |
        yum -y install cmake \
                       gcc \
                       libomp \
                       boost-devel \
                       boost-json

  pre_build:
    commands:
      - echo "Setting up the environment..."
      - export VERSION=$(grep -oP '\[\K[0-9]+\.[0-9]+\.[0-9]+' CHANGELOG.md | head -1)
      - |
        if [ "$CODEBUILD_WEBHOOK_TRIGGER" == "branch/main" ]; then
          export FUCTION_NAME="SudokuSolverBackend"
          export CMAKE_BUILD_TYPE="Release"
          export GIT_REVISION=$(git rev-list HEAD --count)
          export ARTIFACT_NAME="${CMAKE_BUILD_TYPE}/${VERSION}/${GIT_REVISION}"
        else
          export FUCTION_NAME="SudokuSolverBackendStage"
          export CMAKE_BUILD_TYPE="Debug"
          export DATE=$(date +%Y%m%d%H%M%S)
          export ARTIFACT_NAME="${CMAKE_BUILD_TYPE}/${VERSION}/${DATE}"
        fi
      - echo "CMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE"
      - echo "VERSION=$VERSION"
      - echo "ARTIFACT_NAME=$ARTIFACT_NAME"

  build:
    commands:
      - cd $CODEBUILD_SRC_DIR/backend
      - echo "Building external projects..."
      - |
        cmake -S extern/aws-lambda-cpp/ \
              -B extern/aws-lambda-cpp/build \
              -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE \
              -DCMAKE_INSTALL_PREFIX=. \
              -DBUILD_SHARED_LIBS=OFF
        cmake --build extern/aws-lambda-cpp/build -j
        cmake --install extern/aws-lambda-cpp/build
      - echo "Building the application..."
      - |
        cmake -S . \
              -B build \
              -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE \
              -DCMAKE_PREFIX_PATH=.
        cmake --build build -j
      - echo "Running Tests..."
      - ctest --test-dir build --verbose --output-on-failure -j
      - echo "Running Benchmarks..."
      - ./bin/bench
      - echo "Building package..."
      - cmake --build build --target aws-lambda-package-$FUCTION_NAME

  post_build:
    commands:
      - |
        if [ "$CODEBUILD_WEBHOOK_TRIGGER" == "branch/main" ]; then
          echo "Tagging the version..."
          git tag ${VERSION}-${GIT_REVISION}
          git push origin ${VERSION}-${GIT_REVISION}
          echo "Tagged the version: ${VERSION}-${GIT_REVISION}"
        fi
        if [ -f $CODEBUILD_SRC_DIR/backend/build/src/handler/$FUCTION_NAME.zip ]; then
          echo "Uploading to aws lambda"
          aws lambda update-function-code --function-name $FUCTION_NAME --zip-file fileb://$CODEBUILD_SRC_DIR/backend/build/src/handler/$FUCTION_NAME.zip
        fi

reports:
  unittest-reports:
    base-directory: backend/build/tests/unittest-reports
    files: "*.xml"
    discard-paths: yes
    file-format: JUNITXML

artifacts:
  files: backend/build/src/handler/SudokuSolverBackend.zip
  name: $ARTIFACT_NAME
  discard-paths: yes
